#let cpp = box[C#h(-0.1em)++\u{2060}]
#import "@preview/dashy-todo:0.1.3": todo

#todo(position: "inline")[ Rewrite. Just an AI mockup.]

The Template Numerical Library (TNL) is a #cpp library for numerical simulations that aims to combine high computational efficiency with a user-friendly and consistent programming interface. Its design targets modern parallel hardware, including multi-core CPUs, GPUs, and distributed-memory systems, while avoiding the overheads that often follow from traditional object-oriented abstractions. Instead, TNL relies on #cpp templates and their specialization mechanisms to generate architecture-specific code at compile time, making it possible to keep a unified interface without sacrificing performance.

#todo[ Cite TNL paper and PyTNL readme ]

This design is particularly important for GPU computing, where efficient implementations require careful control over memory layout, data transfer, and parallel execution patterns. In many numerical applications, especially those involving sparse matrices, iterative solvers, or mesh-based discretizations, adapting algorithms to accelerators is not a minor extension but a substantial redesign. TNL addresses this difficulty by providing data structures and algorithms that are implemented with these architectural differences in mind, while still presenting a coherent programming model to the user.

More broadly, TNL aims to offer a wider and more coherent environment for #cpp high-performance computing than narrowly specialized libraries. It combines support for common parallel patterns, linear algebra operations, sparse matrices, and numerical solvers under a unified templated interface inspired by the #cpp standard library. This emphasis on consistency and abstraction naturally opens the way to higher-level interfaces that improve usability without giving up the performance advantages of the original library.

One such interface is PyTNL, a Python binding layer for selected TNL components. PyTNL brings TNL into Python-driven workflows, where the convenience and expressiveness of Python can be combined with performance-critical kernels implemented in compiled backends. In this sense, PyTNL can be seen as a further extension of TNL's original focus on user experience: it does not replace the underlying high-performance #cpp library, but makes its selected building blocks more accessible for prototyping, orchestration of numerical workflows, and interoperability with other tools in the Python scientific ecosystem.

At the same time, PyTNL is still under active development and its interface is not yet final. The currently available bindings expose only selected parts of TNL, and the exact set of supported classes and functions may evolve over time. This makes PyTNL both a practical tool and a research opportunity: it already enables useful Python-facing workflows, but it also raises open questions about how far a performance-oriented templated #cpp library can be exposed in a way that remains both efficient and convenient to use.

This thesis focuses on that problem. Its goal is not only to extend PyTNL with additional bindings, but mainly to explore how more advanced TNL abstractions can be made available from Python, especially higher-order operations that in native TNL rely on #cpp lambda functions. A particularly attractive objective is to allow users to express custom computation in Python while still executing performance-critical parts through efficient compiled mechanisms. The central challenge is therefore to improve the user experience of TNL-based workflows without turning the Python interface into a thin but slow wrapper over the original library.

To address this challenge, the thesis examines multiple approaches to crossing the language boundary between Python and #cpp. It first considers direct invocation of Python callables from the native side, then evaluates just-in-time compilation techniques and data interchange protocols that make it possible to operate on TNL-managed memory more directly from Python. These ideas are finally discussed in the context of practical workflows, including the TNL-SPH solver, where improving accessibility and reducing the amount of required boilerplate can significantly enhance the overall usability of the library.