#import "ctufit-thesis.typ": *

Scientific computing increasingly relies on high-level environments such as Python for prototyping, data analysis, and orchestration, while performance-critical kernels remain implemented in low-level languages such as C++ and CUDA. This division of roles makes it important for high-performance numerical libraries to provide interfaces that are both efficient and accessible to users who do not want to work directly with complex C++ code.

The Template Numerical Library (TNL) is a #cpp library for high-performance numerical simulations that targets modern parallel hardware, including multi-core CPUs and NVIDIA GPUs via CUDA. Its design emphasizes generic programming and performance portability, but this also raises the barrier to entry for users unfamiliar with #cpp templates and build systems. PyTNL, the Python binding layer for TNL, aims to make TNL's computational capabilities accessible from Python without sacrificing the performance that makes TNL valuable in the first place.

Two fundamental obstacles arise when exposing a GPU-capable #cpp library to Python. First, higher-order functions such as `forElements` and `parallelFor` — which are central to TNL's programming model — expect #cpp or CUDA lambdas as callbacks. Accepting ordinary Python callables in their place incurs a language-boundary crossing on every element access, which is typically too costly for large-scale computations. Second, the data held in TNL arrays often resides in GPU memory. Any interface that forces unnecessary copies between devices, or even between host buffers, can negate the performance gains that motivated using GPU acceleration at all.

The primary objective of this thesis is therefore to provide a practical high-level interface to TNL while preserving efficient execution on both CPUs and GPUs. To this end, the work focuses mainly on Python: it investigates how Python callbacks can be bound through nanobind and, more importantly, how just-in-time compilation via Numba can elevate Python functions to near-native performance. It also implements three standard data-interchange protocols — the Python Buffer Protocol, the CUDA Array Interface, and DLPack — that allow TNL arrays to expose their underlying memory as a zero-copy view to any compatible consumer library. In addition, the thesis briefly considers Julia as another promising interface for scientific computing because of its ease of use and its performance-oriented design, which may avoid some of the limitations that make efficient Python integration difficult.

The practical value of these contributions is demonstrated on TNL-SPH, an open-source Smoothed Particle Hydrodynamics solver built on TNL. The objective is to replace a workflow based on manual #cpp configuration, CMake builds, and subprocess orchestration with a single Python-driven workflow that is accessible to users without detailed knowledge of C++ or build systems.

The thesis is structured as follows. The first chapter introduces the key components the work builds upon: TNL, PyTNL, the CUDA programming model, the nanobind binding library, and comparable numerical libraries that serve as reference points. The second chapter addresses higher-order functions — how they are used in TNL, what constraints nanobind imposes when Python callables are passed as callbacks, and how Numba JIT compilation and NVRTC-based GPU kernel compilation can overcome the performance gap. The third chapter covers data-interchange protocols, explaining how TNL arrays can satisfy the requirements of the Python Array API Standard and how Numba can then operate directly on TNL memory without any copy. The fourth chapter presents the TNL-SPH demonstration case, showing the improvements in the user workflow that the preceding work makes possible. The final chapter briefly discusses the potential benefits of a Julia interface to TNL and outlines tools that could be used to build the necessary bindings.
